# Generated by Django 3.0.1 on 2020-01-14 02:22

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_cd', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chome',
            fields=[
                ('chome_cd', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('chome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_no', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('member_name', models.TextField()),
                ('mail', models.TextField()),
                ('tel', models.TextField()),
                ('manager_flg', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('dtime', models.DecimalField(decimal_places=0, max_digits=14)),
                ('detail', models.CharField(blank=True, max_length=64)),
                ('member_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('category_cd', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('chome_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='ac01.Chome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
