# Generated by Django 3.0.1 on 2020-01-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac01', '0002_auto_20200114_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
