# Generated by Django 3.0.1 on 2020-01-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac01', '0003_auto_20200114_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chome',
            old_name='chome_cd',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='chome_cd',
            new_name='chome',
        ),
        migrations.AlterField(
            model_name='photo',
            name='dtime',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
